name: CI Pipeline

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install system dependencies
      run: sudo apt-get install -y libpq-dev python3-dev
      
    - name: Install modern Poetry
      run: |
        pip install --upgrade pip
        pip install poetry==1.8.2  # Явно указываем стабильную версию
        
    - name: Validate Poetry installation
      run: poetry --version
      
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: pip install poetry==1.8.2
    - run: poetry install --only dev
    - run: make lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: pip install poetry==1.8.2
    - run: poetry install
    - run: pytest -v --cov=app --cov-report=term-missing
