name: CI Pipeline

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install system dependencies
      run: sudo apt-get install -y libpq-dev python3-dev
    - name: Install Poetry
      run: pip install poetry==1.8.2
    - name: Cache Poetry virtualenv
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: poetry-${{ hashFiles('pyproject.toml') }}

  lint_and_test:
    needs: setup
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install Poetry
      run: pip install poetry==1.8.2
    - name: Install dependencies
      run: |
        poetry install --all-extras
        poetry show
    - name: Run lint
      run: |
        black --check .
        isort --check .
        flake8 .
    - name: Run tests
      env:
        POSTGRES_USER: testuser
        POSTGRES_PASSWORD: testpass
        POSTGRES_DB: testdb
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
      run: |
        python -m pytest -v --cov=app --cov-report=term-missing
